# Generated by Django 3.1.3 on 2020-11-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.URLField(default=''),
        ),
    ]
