# Generated by Django 3.1.3 on 2020-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_experience_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.URLField(),
        ),
    ]
