# Generated by Django 3.1.3 on 2020-11-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201109_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
