# Generated by Django 3.1.3 on 2020-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201109_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_type', models.CharField(choices=[('AV', 'Advanced'), ('IM', 'Intermediate'), ('B', 'Beginner')], default='B', max_length=2)),
            ],
        ),
    ]
