# Generated by Django 3.1.3 on 2020-11-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
