# Generated by Django 3.1.3 on 2020-11-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201109_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(choices=[('AV', 'Advanced'), ('IM', 'Intermediate'), ('B', 'Beginner')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('E', 'Endorsements'), ('IK', 'Industry Knowledge'), ('TT', 'Tools & Technologies'), ('IS', 'Interpersonal Skills'), ('L', 'Languages'), ('OS', 'Other Skills')], default='OS', max_length=2),
        ),
    ]
