# Generated by Django 3.1.3 on 2020-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201109_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('course_start', models.DateTimeField(verbose_name='Job Start')),
                ('course_end', models.DateTimeField(verbose_name='Job End')),
                ('academy_logo', models.URLField()),
                ('course_type', models.CharField(choices=[('BENG', "Bachelor's degree"), ('MENG', "Master's degree"), ('AS', 'AS Level'), ('GCSE', 'GCSE')], default='GCSE', max_length=4)),
            ],
        ),
    ]
