# Generated by Django 3.1.3 on 2020-11-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201110_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
