# Generated by Django 3.1.3 on 2020-11-10 12:35

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_experience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(default='', upload_to=pages.models.image_upload_to),
        ),
    ]
