# Generated by Django 3.1.3 on 2020-11-10 13:41

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201110_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='academy_logo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(default='', upload_to=pages.models.image_upload_to),
        ),
    ]
